language: java
install: true

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: build
      script:
        - ./gradlew assemble

    - stage: test
      script:
        - ./gradlew check
        - ./gradlew jacocoTestReport
      after_success:
        - curl -s https://codecov.io/bash | bash

    - stage: deployment to staging
      if: branch = develop
      then:
      env:
        - secure: "WcWmVmh92ZLrsLr27k9o/d/17HXB0+2a3KZL7O6UpcERHZBmvX5uQPRkeub7cZsKyMwF5i/fnjDhyJSyf29rTBp27pD+wqSPNluWMH4ujwz7ibzvEgnQIouIfMld2u7j/7yyq2ahum0ZQH8EyJ2Lc/KY+k1xIxChWtKB6p6U01PjdMy231d1jmGHgASFEB8tIrdy8BP2+kg8L2XsaHRz2EFeeVLYQEGV+iX2V1QTXRkY+E8LUWrse3pMCfxqE4nE0Zvf+JkC8Rkfmp161Gs/Opr/PagJnmF0xfEdxecYFvBlVRID+g7vwiJG09R4ULh/Wb+pRPjm+C9BXj2ThxMtRJLiPye5HfXKiaPYvon5Qoj4FDn1tMIvqtNxG6npU+TueelZMGLaN1Fgi1qws6TH+ohFb85s3frdjg+PIGKyZGTU9zuc2hH0TcSMuPHf0qQvCiK/dYYeLTqCXRZeMs4giu72CkF/cLM74BBh+2NLQsfCILFO4ANgZExFhbr3EBI7G5sNrX7vX8xFMHeXFTY76wxY3wOpahAmWeiCG/Gxb47zzZJK/ofMcZSfoHPkmlp/SW+jgxPYA8CCMJHt5YsFB51lIgTN2GqziMm5PF3pEnLovOPJJFqHw6zYmB+hdauRspO+VQ0fmLs1dA8t5eA5CMvUyZMxX3fLnHAp4IvygwQ="
        - secure: "qQPY7d3io7HX5FUH+Eu//+E0sbehBYO8ccVvppNMjo2qSzNsJafCyovukz7T0a1XxFpZ5I+VU1Ol1N74IJn6FwL4GfybnC6Te09zXcH2LjTAHEyMQA1dKKl9N8mxPeo+QFHUzjyDjLT0ZoJWp3vkArSM1W1NcJUO6uMCgUrgGsGJpdunBioHDV8bsGdrlOPbsbcI9U6uC5CRQL1E+Qn5ZKfEK2VFsD6mz66kC+7+IVb6bOld+jKSJap6XngPu0IFEmCVInoRmUlrhV9CQZnNgz4N2SaXqUxvtG9D+1o13p0tWgNgjOF6WqBKk/t9bazYRB/YDckasffbyziIP1hZhSC+SPI6pxlcdnWvM62Lk1TkZGHsnxUm5oRGkGfiUca58EXOV0t2oW0nFfYOI9d2JBdZ/eeIN1HjCCK6jPZKFrCwnKyDy1di3X8uUcVXf2i+ZYQdJveHEdUkvtNGYOYfYrn3so2kbTs6Pyf2y+6Lnqlk6Ts/aqb59MiladSXlZxLmQdgYb4JNJ8EGw9IGIILperdaJ/PBbJWUxPAvDEWmf8TOUPB9/CHfGPfuTiP+SNm94KIx9PQ7ZWbfr7yK5IJ8+I/ReghRECloN3PVk+nzyEBieq7MCmMNBKS+rHpHESbrLYwOEvUSwH+mJVtlms7I9E5nJVeZEIeSoaOg7nfoOY="
      script:
        - skip
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: "Q9zEw8ihUhMQmrpilYsT9y8Zpfgaz4ou04XF/RW8UnEcLBop5xX+MSHXtZV3wxluesWK1Y0e4CbzGJe/nqE1naWkXGvmIFWWe61AvKkfE5WqmNwkHvRANxDumFq4xOk2g0JyZTx7+euVYfQ9kD4H4Y1VsY8RBgy1AsGaPdest0o7JafIzXp/kzBGv8Vpno9tUycsyrpjYYmdqi0p3FKqnhA1E9c3uUQhd6Obauvw6pcU5RgiNY+XZTbrXFwzkPz7qLdTHOQO/qmtO1+/WReg/4Pmag+LJThoLZVwmq7p/K8R/Jq9sz9Weiqezh8K6BKqElPwuclrdy8+hSO4ypkWP/Jeaa+bh9SQcUWOPPTamirFmzLiRjK0We4CTe1tlibOtybDmQO05RcPrrahzrmnxEv23lvpnlJWw78fUVJbgdhoRkqMBIIxonxFWxMqEroxwTHen8HoO3KSQ4XPUTvmhRt3MkoFsxn9JWBieKuYq9hTvf34SIir75EF1k/60HxC0RQK8BzSM5cmBmCd/USO9SXFkO9GBkZcArDsDsiT5DPTMut+UgB/h/ha/Qi1fbG8+Ln8tSPNHxpiKWfgC5V9TyZkJPahZ8viB7ykCUlS/DzomVIstjMe0rcO0ryFjUVYb2zVxpCFwkgQcgcHtJCbkURdiL8dAf60vdvqXMrjgFU="
        app:
          develop: board-up-staging
      after_deploy:
        - curl http://wspologarniacz-staging.herokuapp.com/public/swagger-ui.html

    - stage: deployment to production
      if: branch = master
      then:
      env:
        - secure: "WcWmVmh92ZLrsLr27k9o/d/17HXB0+2a3KZL7O6UpcERHZBmvX5uQPRkeub7cZsKyMwF5i/fnjDhyJSyf29rTBp27pD+wqSPNluWMH4ujwz7ibzvEgnQIouIfMld2u7j/7yyq2ahum0ZQH8EyJ2Lc/KY+k1xIxChWtKB6p6U01PjdMy231d1jmGHgASFEB8tIrdy8BP2+kg8L2XsaHRz2EFeeVLYQEGV+iX2V1QTXRkY+E8LUWrse3pMCfxqE4nE0Zvf+JkC8Rkfmp161Gs/Opr/PagJnmF0xfEdxecYFvBlVRID+g7vwiJG09R4ULh/Wb+pRPjm+C9BXj2ThxMtRJLiPye5HfXKiaPYvon5Qoj4FDn1tMIvqtNxG6npU+TueelZMGLaN1Fgi1qws6TH+ohFb85s3frdjg+PIGKyZGTU9zuc2hH0TcSMuPHf0qQvCiK/dYYeLTqCXRZeMs4giu72CkF/cLM74BBh+2NLQsfCILFO4ANgZExFhbr3EBI7G5sNrX7vX8xFMHeXFTY76wxY3wOpahAmWeiCG/Gxb47zzZJK/ofMcZSfoHPkmlp/SW+jgxPYA8CCMJHt5YsFB51lIgTN2GqziMm5PF3pEnLovOPJJFqHw6zYmB+hdauRspO+VQ0fmLs1dA8t5eA5CMvUyZMxX3fLnHAp4IvygwQ="
        - secure: "qQPY7d3io7HX5FUH+Eu//+E0sbehBYO8ccVvppNMjo2qSzNsJafCyovukz7T0a1XxFpZ5I+VU1Ol1N74IJn6FwL4GfybnC6Te09zXcH2LjTAHEyMQA1dKKl9N8mxPeo+QFHUzjyDjLT0ZoJWp3vkArSM1W1NcJUO6uMCgUrgGsGJpdunBioHDV8bsGdrlOPbsbcI9U6uC5CRQL1E+Qn5ZKfEK2VFsD6mz66kC+7+IVb6bOld+jKSJap6XngPu0IFEmCVInoRmUlrhV9CQZnNgz4N2SaXqUxvtG9D+1o13p0tWgNgjOF6WqBKk/t9bazYRB/YDckasffbyziIP1hZhSC+SPI6pxlcdnWvM62Lk1TkZGHsnxUm5oRGkGfiUca58EXOV0t2oW0nFfYOI9d2JBdZ/eeIN1HjCCK6jPZKFrCwnKyDy1di3X8uUcVXf2i+ZYQdJveHEdUkvtNGYOYfYrn3so2kbTs6Pyf2y+6Lnqlk6Ts/aqb59MiladSXlZxLmQdgYb4JNJ8EGw9IGIILperdaJ/PBbJWUxPAvDEWmf8TOUPB9/CHfGPfuTiP+SNm94KIx9PQ7ZWbfr7yK5IJ8+I/ReghRECloN3PVk+nzyEBieq7MCmMNBKS+rHpHESbrLYwOEvUSwH+mJVtlms7I9E5nJVeZEIeSoaOg7nfoOY="
      script:
        - skip
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: "Q9zEw8ihUhMQmrpilYsT9y8Zpfgaz4ou04XF/RW8UnEcLBop5xX+MSHXtZV3wxluesWK1Y0e4CbzGJe/nqE1naWkXGvmIFWWe61AvKkfE5WqmNwkHvRANxDumFq4xOk2g0JyZTx7+euVYfQ9kD4H4Y1VsY8RBgy1AsGaPdest0o7JafIzXp/kzBGv8Vpno9tUycsyrpjYYmdqi0p3FKqnhA1E9c3uUQhd6Obauvw6pcU5RgiNY+XZTbrXFwzkPz7qLdTHOQO/qmtO1+/WReg/4Pmag+LJThoLZVwmq7p/K8R/Jq9sz9Weiqezh8K6BKqElPwuclrdy8+hSO4ypkWP/Jeaa+bh9SQcUWOPPTamirFmzLiRjK0We4CTe1tlibOtybDmQO05RcPrrahzrmnxEv23lvpnlJWw78fUVJbgdhoRkqMBIIxonxFWxMqEroxwTHen8HoO3KSQ4XPUTvmhRt3MkoFsxn9JWBieKuYq9hTvf34SIir75EF1k/60HxC0RQK8BzSM5cmBmCd/USO9SXFkO9GBkZcArDsDsiT5DPTMut+UgB/h/ha/Qi1fbG8+Ln8tSPNHxpiKWfgC5V9TyZkJPahZ8viB7ykCUlS/DzomVIstjMe0rcO0ryFjUVYb2zVxpCFwkgQcgcHtJCbkURdiL8dAf60vdvqXMrjgFU="
        app:
          master: board-up
      after_deploy:
        - curl http://wspologarniacz.herokuapp.com/public/swagger-ui.html

