language: java
install: true

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: build
      script:
        - ./gradlew assemble

    - stage: test
      script:
        - ./gradlew check
        - ./gradlew jacocoTestReport
      after_success:
        - curl -s https://codecov.io/bash | bash

    - stage: deployment to staging
      if: branch = develop
      then:
      env:
        - secure: "WcWmVmh92ZLrsLr27k9o/d/17HXB0+2a3KZL7O6UpcERHZBmvX5uQPRkeub7cZsKyMwF5i/fnjDhyJSyf29rTBp27pD+wqSPNluWMH4ujwz7ibzvEgnQIouIfMld2u7j/7yyq2ahum0ZQH8EyJ2Lc/KY+k1xIxChWtKB6p6U01PjdMy231d1jmGHgASFEB8tIrdy8BP2+kg8L2XsaHRz2EFeeVLYQEGV+iX2V1QTXRkY+E8LUWrse3pMCfxqE4nE0Zvf+JkC8Rkfmp161Gs/Opr/PagJnmF0xfEdxecYFvBlVRID+g7vwiJG09R4ULh/Wb+pRPjm+C9BXj2ThxMtRJLiPye5HfXKiaPYvon5Qoj4FDn1tMIvqtNxG6npU+TueelZMGLaN1Fgi1qws6TH+ohFb85s3frdjg+PIGKyZGTU9zuc2hH0TcSMuPHf0qQvCiK/dYYeLTqCXRZeMs4giu72CkF/cLM74BBh+2NLQsfCILFO4ANgZExFhbr3EBI7G5sNrX7vX8xFMHeXFTY76wxY3wOpahAmWeiCG/Gxb47zzZJK/ofMcZSfoHPkmlp/SW+jgxPYA8CCMJHt5YsFB51lIgTN2GqziMm5PF3pEnLovOPJJFqHw6zYmB+hdauRspO+VQ0fmLs1dA8t5eA5CMvUyZMxX3fLnHAp4IvygwQ="
        - secure: "qQPY7d3io7HX5FUH+Eu//+E0sbehBYO8ccVvppNMjo2qSzNsJafCyovukz7T0a1XxFpZ5I+VU1Ol1N74IJn6FwL4GfybnC6Te09zXcH2LjTAHEyMQA1dKKl9N8mxPeo+QFHUzjyDjLT0ZoJWp3vkArSM1W1NcJUO6uMCgUrgGsGJpdunBioHDV8bsGdrlOPbsbcI9U6uC5CRQL1E+Qn5ZKfEK2VFsD6mz66kC+7+IVb6bOld+jKSJap6XngPu0IFEmCVInoRmUlrhV9CQZnNgz4N2SaXqUxvtG9D+1o13p0tWgNgjOF6WqBKk/t9bazYRB/YDckasffbyziIP1hZhSC+SPI6pxlcdnWvM62Lk1TkZGHsnxUm5oRGkGfiUca58EXOV0t2oW0nFfYOI9d2JBdZ/eeIN1HjCCK6jPZKFrCwnKyDy1di3X8uUcVXf2i+ZYQdJveHEdUkvtNGYOYfYrn3so2kbTs6Pyf2y+6Lnqlk6Ts/aqb59MiladSXlZxLmQdgYb4JNJ8EGw9IGIILperdaJ/PBbJWUxPAvDEWmf8TOUPB9/CHfGPfuTiP+SNm94KIx9PQ7ZWbfr7yK5IJ8+I/ReghRECloN3PVk+nzyEBieq7MCmMNBKS+rHpHESbrLYwOEvUSwH+mJVtlms7I9E5nJVeZEIeSoaOg7nfoOY="
      script:
        - skip
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: aZHnJlL6J28hHh5Nb+2MAbhh45CqV4AkkJKnC1X9WcN/rcajeptJLnNrjERpgHhmCcLp3LAlCeK41ByyoSRGgWXw37zawm0RuTlrGhywFw3nEEPWOBsz9Ft/RKC+hNeWgnDIj70MYObbIej4HIXuteDNBD8fKItBJ+07s4prtnGKO0S239iIu4MgoLe+8ED9y/D6p0NBdLL1sGh/rSuRbqC5HN3x+K+djk1NjHUKDWoMFRM/hQWOvvgbuu1HXeNfy1jou1PTNXg5P1p9BqoiT55f+CC/moOelTXTdisGOPPJj2JJbXHx8dvabBoxpLnoAKxI5a6Bi+WOsrCLT49k2tdNsqjqjFQXy4wIwa9r4AZBY1mxWIOc6RaixRdlWNH0DDP9Cxc334INtW+gfU5I8Hjse207YpXRWo6rUpDSI7o8l3ibe1CJPZ9wgS4dY5E5wNzUoXVWLEu1JSGRIx9je36AgOmiirUyS7qma0rdaHaf7uEo53YU3JOP4CholQjgN2jRhyuq9kMI5bwa1DGkgR09qWpJNK7hGCkogDL3RBljxRkh33NjwI5GwzSi9lAESqsfgX2aUizOH6pqEEdUHY7oQ85qqj7Zt/2clmwCk7xtRCCiUS8qjOLQu/fP+xDZ49wxqsTteDPWJaxBdP7xzxyV77F18Yr6TA5PYj6wiAA=
        app:
          develop: board-up-staging
      after_deploy:
        - curl http://board-up-staging.herokuapp.com/public/swagger-ui.html

    - stage: deployment to production
      if: branch = master
      then:
      env:
        - secure: "WcWmVmh92ZLrsLr27k9o/d/17HXB0+2a3KZL7O6UpcERHZBmvX5uQPRkeub7cZsKyMwF5i/fnjDhyJSyf29rTBp27pD+wqSPNluWMH4ujwz7ibzvEgnQIouIfMld2u7j/7yyq2ahum0ZQH8EyJ2Lc/KY+k1xIxChWtKB6p6U01PjdMy231d1jmGHgASFEB8tIrdy8BP2+kg8L2XsaHRz2EFeeVLYQEGV+iX2V1QTXRkY+E8LUWrse3pMCfxqE4nE0Zvf+JkC8Rkfmp161Gs/Opr/PagJnmF0xfEdxecYFvBlVRID+g7vwiJG09R4ULh/Wb+pRPjm+C9BXj2ThxMtRJLiPye5HfXKiaPYvon5Qoj4FDn1tMIvqtNxG6npU+TueelZMGLaN1Fgi1qws6TH+ohFb85s3frdjg+PIGKyZGTU9zuc2hH0TcSMuPHf0qQvCiK/dYYeLTqCXRZeMs4giu72CkF/cLM74BBh+2NLQsfCILFO4ANgZExFhbr3EBI7G5sNrX7vX8xFMHeXFTY76wxY3wOpahAmWeiCG/Gxb47zzZJK/ofMcZSfoHPkmlp/SW+jgxPYA8CCMJHt5YsFB51lIgTN2GqziMm5PF3pEnLovOPJJFqHw6zYmB+hdauRspO+VQ0fmLs1dA8t5eA5CMvUyZMxX3fLnHAp4IvygwQ="
        - secure: "qQPY7d3io7HX5FUH+Eu//+E0sbehBYO8ccVvppNMjo2qSzNsJafCyovukz7T0a1XxFpZ5I+VU1Ol1N74IJn6FwL4GfybnC6Te09zXcH2LjTAHEyMQA1dKKl9N8mxPeo+QFHUzjyDjLT0ZoJWp3vkArSM1W1NcJUO6uMCgUrgGsGJpdunBioHDV8bsGdrlOPbsbcI9U6uC5CRQL1E+Qn5ZKfEK2VFsD6mz66kC+7+IVb6bOld+jKSJap6XngPu0IFEmCVInoRmUlrhV9CQZnNgz4N2SaXqUxvtG9D+1o13p0tWgNgjOF6WqBKk/t9bazYRB/YDckasffbyziIP1hZhSC+SPI6pxlcdnWvM62Lk1TkZGHsnxUm5oRGkGfiUca58EXOV0t2oW0nFfYOI9d2JBdZ/eeIN1HjCCK6jPZKFrCwnKyDy1di3X8uUcVXf2i+ZYQdJveHEdUkvtNGYOYfYrn3so2kbTs6Pyf2y+6Lnqlk6Ts/aqb59MiladSXlZxLmQdgYb4JNJ8EGw9IGIILperdaJ/PBbJWUxPAvDEWmf8TOUPB9/CHfGPfuTiP+SNm94KIx9PQ7ZWbfr7yK5IJ8+I/ReghRECloN3PVk+nzyEBieq7MCmMNBKS+rHpHESbrLYwOEvUSwH+mJVtlms7I9E5nJVeZEIeSoaOg7nfoOY="
      script:
        - skip
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: aZHnJlL6J28hHh5Nb+2MAbhh45CqV4AkkJKnC1X9WcN/rcajeptJLnNrjERpgHhmCcLp3LAlCeK41ByyoSRGgWXw37zawm0RuTlrGhywFw3nEEPWOBsz9Ft/RKC+hNeWgnDIj70MYObbIej4HIXuteDNBD8fKItBJ+07s4prtnGKO0S239iIu4MgoLe+8ED9y/D6p0NBdLL1sGh/rSuRbqC5HN3x+K+djk1NjHUKDWoMFRM/hQWOvvgbuu1HXeNfy1jou1PTNXg5P1p9BqoiT55f+CC/moOelTXTdisGOPPJj2JJbXHx8dvabBoxpLnoAKxI5a6Bi+WOsrCLT49k2tdNsqjqjFQXy4wIwa9r4AZBY1mxWIOc6RaixRdlWNH0DDP9Cxc334INtW+gfU5I8Hjse207YpXRWo6rUpDSI7o8l3ibe1CJPZ9wgS4dY5E5wNzUoXVWLEu1JSGRIx9je36AgOmiirUyS7qma0rdaHaf7uEo53YU3JOP4CholQjgN2jRhyuq9kMI5bwa1DGkgR09qWpJNK7hGCkogDL3RBljxRkh33NjwI5GwzSi9lAESqsfgX2aUizOH6pqEEdUHY7oQ85qqj7Zt/2clmwCk7xtRCCiUS8qjOLQu/fP+xDZ49wxqsTteDPWJaxBdP7xzxyV77F18Yr6TA5PYj6wiAA=
        app:
          master: board-up
      after_deploy:
        - curl http://board-up.herokuapp.com/public/swagger-ui.html

